credentials:
  usernames:
    jsmith: # Example user
      email: "jsmith@example.com"
      name: "John Smith"
      password: "PASTE_YOUR_FIRST_HASHED_PASSWORD_HERE" # e.g., '$2b$12$...'

    admin: # Example admin user
      email: "admin@example.com"
      name: "Admin User"
      password: "PASTE_YOUR_SECOND_HASHED_PASSWORD_HERE" # e.g., '$2b$12$...'

cookie:
  name: "internal_docs_qa_cookie"
  key: "PASTE_YOUR_LONG_RANDOM_HEX_STRING_HERE" # <-- THIS IS THE NEW SECRET KEY
  expiry_days: 30

preauthorized:
  emails:
    - "admin@example.com"